const service = require('../services/authService')

exports.register = (req, res) => service.register(req, res)
exports.login = (req, res) => service.login(req, res)
exports.refresh = (req, res) => service.refresh(req, res)
exports.logout = (req, res) => service.logout(req, res)
exports.me = (req, res) => service.me(req, res)
exports.verifyToken = (req, res) => service.verifyToken(req, res)
exports.googleRedirect = (req, res) => service.googleRedirect(req, res)
exports.googleCallback = (req, res) => service.googleCallback(req, res)